---
name: "Commit"

on:
  push:
    branches:
      - master

jobs:
  distribute:
    name: Distribute
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version: 3.9
      fail-fast: false
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: {{ matrix.python-version }}
      - name: Install the dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          password: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
      - name: Publish the README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          password: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
          repository: seiso/easy_sast
      - name: Publish the latest docker image
        run: invoke publish latest