---
name: "Security"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '27 3 * * *'

jobs:
  analyze:
    name: CodeQL
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the dependencies
        run: |
          pip install -r requirements.txt -r veracode/requirements.txt
          echo "CODEQL_PYTHON=$(which python)" >> "${GITHUB_ENV}"
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
